### ISSUE TITLE
Future Features

### ISSUE THREAD

**Issue by zachgibson** [saranshsolanki/sketch-lint#3]
Do you have any plans to incorporate platform design linting rules?

e.g. Rules for designing a website where overlapping bounding boxes would be an error because you have to use something like `position: absolute;` or a negative margin to achieve it.

**Comment by saranshsolanki** [comment]
Yes. I'm currently working on adding accessibility rules. Platform guidelines coming in next.

**Comment by zachgibson** [comment]
Nice! Can’t wait to see what that looks like.
